In [3]:
import pandas as pd
import statsmodels.formula.api as sm
import numpy as np

In [2]:
data = pd.read_csv('hw4.csv')

data.head()

   Price    Sales  Engine_size  Fuel_capacity  Fuel_efficiency  Car_Brand
0  21.50  21.9947          1.8           13.2               28          3
1  28.40  39.3840          3.2           17.2               25          2
2  42.00  15.4584          3.5           18.0               22          4
3  23.99  14.2779          1.8           16.4               27          1
4  33.95  13.1460          2.8           18.5               22          1

### Question 1

In [4]:
data['ln_price'] = np.log(data['Price'])
data['ln_sales'] = np.log(data['Sales'])

data.head()

,Price,Sales,Engine_size,Fuel_capacity,Fuel_efficiency,Car_Brand,ln_price,ln_sales
0,21.50,21.9947,1.8,13.2,28,3,3.068053,3.090802
1,28.40,39.3840,3.2,17.2,25,2,3.346389,3.673360
2,42.00,15.4584,3.5,18.0,22,4,3.737670,2.738153
3,23.99,14.2779,1.8,16.4,27,1,3.177637,2.658713
4,33.95,13.1460,2.8,18.5,22,1,3.524889,2.576118

In [5]:
result1 = sm.ols('ln_sales ~ ln_price', data = data).fit()

print(result1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               ln_sales   R-squared:                       0.263
Model:                            OLS   Adj. R-squared:                  0.258
Method:                 Least Squares   F-statistic:                     53.92
Date:                Thu, 02 Dec 2021   Prob (F-statistic):           1.21e-11
Time:                        13:28:03   Log-Likelihood:                -239.83
No. Observations:                 153   AIC:                             483.7
Df Residuals:                     151   BIC:                             489.7
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.2954      0.667     12.428      0.000       6.977       9.614
ln_price      -1.5159      0.206     -7.343      0.000      -1.924      -1.108
==============================================================================
Omnibus:                       22.474   Durbin-Watson:                   1.478
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               44.840
Skew:                          -0.657   Prob(JB):                     1.83e-10
Kurtosis:                       5.304   Cond. No.                         25.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Question 2

In [7]:
data['brand_1'] = [1 if i == 1 else 0 for i in data['Car_Brand']]
data['brand_2'] = [1 if i == 2 else 0 for i in data['Car_Brand']]
data['brand_3'] = [1 if i == 3 else 0 for i in data['Car_Brand']]

data.head()

,Price,Sales,Engine_size,Fuel_capacity,Fuel_efficiency,Car_Brand,ln_price,ln_sales,brand_1,brand_2,brand_3
0,21.50,21.9947,1.8,13.2,28,3,3.068053,3.090802,0,0,1
1,28.40,39.3840,3.2,17.2,25,2,3.346389,3.673360,0,1,0
2,42.00,15.4584,3.5,18.0,22,4,3.737670,2.738153,0,0,0
3,23.99,14.2779,1.8,16.4,27,1,3.177637,2.658713,1,0,0
4,33.95,13.1460,2.8,18.5,22,1,3.524889,2.576118,1,0,0

In [10]:
result2 = sm.ols('ln_sales ~ ln_price + Engine_size + Fuel_capacity + Fuel_efficiency + brand_1 + brand_2 + brand_3', data = data).fit()

print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               ln_sales   R-squared:                       0.402
Model:                            OLS   Adj. R-squared:                  0.373
Method:                 Least Squares   F-statistic:                     13.93
Date:                Thu, 02 Dec 2021   Prob (F-statistic):           9.86e-14
Time:                        13:56:43   Log-Likelihood:                -223.84
No. Observations:                 153   AIC:                             463.7
Df Residuals:                     145   BIC:                             487.9
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           8.5809      1.771      4.845      0.000       5.080      12.081
ln_price           -2.2334      0.260     -8.595      0.000      -2.747      -1.720
Engine_size         0.2946      0.137      2.147      0.033       0.023       0.566
Fuel_capacity       0.0773      0.038      2.021      0.045       0.002       0.153
Fuel_efficiency     0.0043      0.039      0.109      0.914      -0.073       0.082
brand_1            -0.8374      0.240     -3.491      0.001      -1.311      -0.363
brand_2            -0.3649      0.237     -1.541      0.125      -0.833       0.103
brand_3            -0.4643      0.248     -1.875      0.063      -0.954       0.025
==============================================================================
Omnibus:                       56.060   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              194.132
Skew:                          -1.370   Prob(JB):                     7.00e-43
Kurtosis:                       7.790   Cond. No.                         619.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Question 3

In [12]:
result3 = sm.ols('Sales ~ Price + Engine_size + Fuel_capacity + Fuel_efficiency + brand_1 + brand_2 + brand_3', data = data).fit()

print(result3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.226
Model:                            OLS   Adj. R-squared:                  0.189
Method:                 Least Squares   F-statistic:                     6.051
Date:                Thu, 02 Dec 2021   Prob (F-statistic):           3.33e-06
Time:                        14:05:15   Log-Likelihood:                -912.03
No. Observations:                 153   AIC:                             1840.
Df Residuals:                     145   BIC:                             1864.
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         -95.8377    140.557     -0.682      0.496    -373.642     181.967
Price              -3.2050      0.703     -4.560      0.000      -4.594      -1.816
Engine_size        22.6694     12.550      1.806      0.073      -2.136      47.475
Fuel_capacity       7.4067      3.434      2.157      0.033       0.619      14.195
Fuel_efficiency     4.0720      3.476      1.172      0.243      -2.798      10.942
brand_1           -81.9958     21.549     -3.805      0.000    -124.586     -39.405
brand_2           -61.7647     21.309     -2.899      0.004    -103.881     -19.648
brand_3           -65.2593     22.268     -2.931      0.004    -109.270     -21.248
==============================================================================
Omnibus:                      181.839   Durbin-Watson:                   1.350
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7064.679
Skew:                           4.454   Prob(JB):                         0.00
Kurtosis:                      35.075   Cond. No.                         755.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Question 4

In [14]:
result4 = sm.ols('ln_sales ~ ln_price + Engine_size + Fuel_capacity + Fuel_efficiency + ln_price*brand_1 + ln_price*brand_2 + ln_price*brand_3', data = data).fit()

print(result4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               ln_sales   R-squared:                       0.431
Model:                            OLS   Adj. R-squared:                  0.391
Method:                 Least Squares   F-statistic:                     10.74
Date:                Thu, 02 Dec 2021   Prob (F-statistic):           1.93e-13
Time:                        14:29:30   Log-Likelihood:                -220.10
No. Observations:                 153   AIC:                             462.2
Df Residuals:                     142   BIC:                             495.5
Df Model:                          10
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           10.9267      2.078      5.259      0.000       6.820      15.034
ln_price            -2.8869      0.383     -7.538      0.000      -3.644      -2.130
Engine_size          0.3330      0.136      2.447      0.016       0.064       0.602
Fuel_capacity        0.0578      0.039      1.477      0.142      -0.020       0.135
Fuel_efficiency      0.0033      0.040      0.082      0.935      -0.075       0.081
brand_1             -4.9914      1.677     -2.976      0.003      -8.307      -1.676
ln_price:brand_1     1.2848      0.513      2.504      0.013       0.270       2.299
brand_2             -3.7223      1.848     -2.015      0.046      -7.375      -0.070
ln_price:brand_2     1.0607      0.583      1.821      0.071      -0.091       2.212
brand_3             -2.3502      1.668     -1.409      0.161      -5.647       0.947
ln_price:brand_3     0.5938      0.515      1.152      0.251      -0.425       1.612
==============================================================================
Omnibus:                       57.122   Durbin-Watson:                   1.735
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              211.007
Skew:                          -1.371   Prob(JB):                     1.51e-46
Kurtosis:                       8.058   Cond. No.                         995.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.